// import "dotenv/config";
// import { PrismaClient } from "../../generated/prisma/client";

// const prisma = new PrismaClient();
// export { PrismaClient };
// export { prisma };
//--------------------------------------------------------------------

import "dotenv/config";
import { PrismaClient } from "../../generated/prisma/client";

/*
* prisma client used for database operations.
* It is an instance of the PrismaClient class generated by Prisma based on the schema defined in the project.
* The datasourceUrl option is set to the value of the DATABASE_URL environment variable,
* which should contain the connection string for the database. This allows the application
* to connect to the database and perform CRUD operations on the defined models.
*/
const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL,
});

//exporting the prisma client for use in other parts of the application, such as controllers and services.
export { PrismaClient, prisma };